name: Deploy Backend to DigitalOcean

on:
  push:
    branches:
      - master

env:
  OUTPUT_DIR: /root/app # Define the output directory variable
  APP_NAME: my-app # Define the output directory variable

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn

      - name: Build the backend
        run: yarn build

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PARKBNB_GH_ACTION_SSHKEY_V2 }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 209.38.8.8 >> ~/.ssh/known_hosts

      - name: Copy files to server
        run: |
          scp package.json root@209.38.8.8:$OUTPUT_DIR
          scp -r src root@209.38.8.8:$OUTPUT_DIR
          scp -r dist root@209.38.8.8:$OUTPUT_DIR
          scp ecosystem.config.js root@209.38.8.8:$OUTPUT_DIR

      - name: Copy .env.production to server
        run: |
          ssh root@209.38.8.8 "cp /root/.env.production $OUTPUT_DIR"

      - name: Install dependencies on server
        run: |
          ssh root@209.38.8.8 "cd $OUTPUT_DIR && yarn install"

      - name: Restart backend application with pm2
        run: |
          ssh root@209.38.8.8 "
            cd $OUTPUT_DIR && pm2 start ecosystem.config.js || pm2 reload $APP_NAME"
