name: Deploy Backend to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: yarn

    - name: Build the backend
      run: yarn build

    - name: Set up SSH
      env:
        SSH_PRIVATE_KEY: ${{ secrets.PARKBNB_GH_ACTION_SSHKEY_V2 }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 209.38.8.8 >> ~/.ssh/known_hosts

    - name: Copy files to server
      run: |
        ls -la
        scp -r dist root@209.38.8.8:/app
        scp -r src root@209.38.8.8:/app
        scp package.json root@209.38.8.8:/app

    - name: Install dependencies on server
      run: |
        ssh root@209.38.8.8 "
          cd /app &&
          yarn install"

    - name: Restart backend application with pm2
      run: |
        ssh root@209.38.8.8 "
          cd /app &&
          pm2 start node -r ./src/env/env-loader.prod.ts ./dist/src/server.js --name my-backend ||
          pm2 reload my-backend"
